'use client';
import {ArrowDown,ArrowUpRight,ArrowRight} from 'lucide-react';
import DataSection from './DataSection';
import CaseStudies from './CaseStudies';
import BenchmarkSection from './BenchmarkSection';
import PublicationLinks from './PublicationLinks';
import Citation from './Citation';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';

export default function Research(){
 return <>
 <BenchmarkSection/>
 <section className="control-section" id="method"><div className="section wrap">
 <div className="section-heading"><div><p className="eyebrow">02 / THE FRAMEWORK</p><h2>Motion. Geometry.<br/><em>Then, the future.</em></h2></div><p>One shared diffusion Transformer predicts optical flow, then pointmaps, then future RGB. Each completed stream is held fixed as context for the next; causal attention blocks information from later stages.</p></div>
<figure className="framework"><a href="./assets/CausalWM_Connected.pdf?v=4430cd7a8437" target="_blank" rel="noreferrer" aria-label="Open the complete CausalWM architecture figure"><img src="./assets/CausalWM_Connected_preview.png?v=4430cd7a8437" width="3200" height="1340" loading="lazy" alt="CausalWM framework: visual context and multimodal conditioning guide causal optical-flow, pointmap and future-RGB prediction, with three training stages and in-context control."/></a><figcaption><span>The CausalWM framework · shared backbone, causal reasoning and visual control</span><a href="./assets/CausalWM_Connected.pdf?v=4430cd7a8437" target="_blank" rel="noreferrer">Open full figure <ArrowUpRight size={16}/></a></figcaption></figure>
 <Accordion className="method-details">
 <AccordionItem value="training"><AccordionTrigger>How CausalWM learns · three training stages</AccordionTrigger><AccordionContent><div className="training-details"><p className="training-intro">About 31K source hours are curated into 20K retained hours across 20 source families. The 16B model uses the video Transformer from LTX-2.3-22B with audio parameters removed, a frozen video VAE and a frozen Gemma-3-12B text encoder.</p><div className="training-stages">{[{n:'01',tag:'PRE-TRAINING',title:'Learn to predict.',text:'Learn embodied video dynamics with text through cross-attention and CD-LAM latent actions through AdaLN. Single-view and multi-view training build the foundation for causal reasoning.',foot:'Pixel-level video generation'},{n:'02',tag:'CAUSAL CoT MID-TRAINING',title:'Learn the intermediate steps.',text:'Randomly choose a target stage, provide preceding variables as clean context and mask later streams. SEA-RAFT supplies optical flow; VGGT-Omega depth and camera intrinsics are lifted into normalized XYZ pointmaps.',foot:'Structured physical context'},{n:'03',tag:'RL POST-TRAINING',title:'Refine the possible futures.',text:'DiffusionNFT samples candidate futures and scores physical consistency, temporal coherence, visual quality and task completion. Group-normalized rewards favor higher-quality predictions and suppress lower-quality ones.',foot:'DiffusionNFT · multi-objective rewards'}].map(t=><article key={t.n}><div className="training-number">{t.n}<ArrowRight size={24}/></div><p className="eyebrow">{t.tag}</p><h3>{t.title}</h3><p>{t.text}</p><span className="training-foot">{t.foot}</span></article>)}</div></div></AccordionContent></AccordionItem>
 <AccordionItem value="control"><AccordionTrigger>How actions guide generation · multi-view visual control</AccordionTrigger><AccordionContent><div className="visual-control-details"><div className="section-grid"><h2>Give the model<br/><em>a path to follow.</em></h2><div><p className="lead">Motion and geometry are also a way to guide generation.</p><p>The supplied joint and gripper trajectories drive a URDF robot renderer. Synchronized head and wrist control videos replace an intermediate visual stream. Fine-tuning teaches the three-view model to follow this visual context when generating future RGB. Compatible visual guidance enters the shared token sequence without redesigning the backbone.</p><div className="control-flow"><span>Robot actions</span><ArrowRight size={16}/><span>Rendered control</span><ArrowRight size={16}/><span>Future views</span></div><p className="tiny-note">Head camera · Left wrist · Right wrist<br/>TriWorldBench rollout: 1 anchor + 8 recent frames → 120 future frames per window. The action-rendering pathway is evaluated here; the camera-guidance pathway in the figure illustrates the broader interface.</p></div></div></div></AccordionContent></AccordionItem>
 </Accordion>
 </div></section>
 <CaseStudies/>
 <DataSection/>
 <section className="research-footer" id="research"><div className="wrap section"><p className="eyebrow">RESEARCH & RESOURCES</p><div className="section-grid"><div><h2>CausalWM</h2><p className="footer-title">Causal Chain-of-Thought Reasoning<br/>for Embodied World Model</p><p className="research-status">CausalWM v1 · Research release</p><PublicationLinks/></div><div className="resource-links"><a href="./assets/CausalWM_Connected.pdf?v=4430cd7a8437" target="_blank" rel="noreferrer"><span>Architecture figure<small>The complete causal CoT framework</small></span><ArrowUpRight/></a><a href="./assets/CausalWM_Comparison.pdf?v=bfa81fd29ed9" target="_blank" rel="noreferrer"><span>Reasoning & benchmark figure<small>Prediction paradigms and headline results</small></span><ArrowUpRight/></a><a href="./data/few-step.csv" download><span>Few-step results<small>All six denoising schedules · CSV</small></span><ArrowDown/></a><a href="./data/triworldbench.csv" download><span>Benchmark comparison<small>Official TriWorldBench top five · CSV</small></span><ArrowDown/></a></div></div><Citation/><div className="footer-bottom"><a href="#top" className="wordmark">CAUSAL<span>WM</span></a><span>Observe. Reason. Predict.</span><a href="#top">Back to top ↑</a></div></div></section>
 </>;
}
